name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build demo
        run: npm run build:demo

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "React Marquee Master ${{ github.ref_name }}" \
            --notes-file RELEASE_NOTES_v2.0.0.md \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        run: |
          cd dev/dist
          zip -r demo-${{ github.ref_name }}.zip .
          gh release upload ${{ github.ref_name }} demo-${{ github.ref_name }}.zip \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
